name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - emacs: 25.1
            ts: false
            lint: true
          - emacs: 27.1
            ts: false
            lint: true
          - emacs: snapshot
            ts: true
            lint: true
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs }}
    - uses: actions/checkout@v4

    - name: Install package-lint
      run: emacs -Q -l .github/workflows/init.el -batch
                    --eval "(package-install 'package-lint)"

    # - name: Lint gams-mode
    #   run: emacs -Q -l .github/workflows/init.el -batch
    #                 -f package-lint-batch-and-exit
    #                 gams-mode.el

    - name: Byte-compile
      run: emacs -Q -l .github/workflows/init.el -batch
                    -L .
                    --eval "(setq byte-compile-error-on-warn t)"
                    -f batch-byte-compile
                    gams-mode.el

    - name: Install texinfo
      run: sudo apt-get update && sudo apt-get install -y texinfo

    - name: Build documentation
      run: makeinfo --no-split doc/gams-mode.texi -o doc/gams-mode.info
